global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using QrToPay.ViewModels.Base;
global using QrToPay.ViewModels;
global using QrToPay.Services;
global using QrToPay.View;
global using QrToPay.Models;
global using QrToPay.Helpers;
global using Microsoft.Maui.Storage;